import type { SiteSettings, Province, Product, Order, User, Supervisor, Notification, Analytics } from '@/types';

// ============ SITE SETTINGS — PayNex ============
export const DEFAULT_SETTINGS: SiteSettings = {
  primaryColor: '#0a1628',
  secondaryColor: '#c9a84c',
  accentColor: '#00d4ff',
  logoUrl: '/src/assets/paynex-logo.png',
  siteNameAr: 'باينكس',
  siteNameEn: 'PayNex',
  taglineAr: 'حلول التقسيط الذكي للجيل القادم',
  taglineEn: 'Smart Installment Solutions for the Next Generation',
  contactPhone: '01000000000',
  contactWhatsapp: '201000000000',
  contactEmail: 'info@paynex.com',
  facebookUrl: 'https://facebook.com/paynex',
  instagramUrl: 'https://instagram.com/paynex',
  twitterUrl: 'https://twitter.com/paynex',
  tiktokUrl: 'https://tiktok.com/@paynex',
  youtubeUrl: 'https://youtube.com/@paynex',
  inquiryFee: 150,
  defaultInterestRate: 0,
  defaultAdminFee: 2,
  minDownPaymentPercent: 0,
  maxInstallmentMonths: 36,
  defaultInstallmentMonths: 12,
  footerTextAr: 'باينكس PayNex — حلول التقسيط الذكي. جميع الحقوق محفوظة 2025',
  footerTextEn: 'PayNex — Smart Installment Solutions. All rights reserved 2025',
  lastSyncDate: new Date().toISOString(),
  syncJsonUrl: '',
  autoSyncEnabled: false,
  autoSyncIntervalHours: 24,
  banners: [
    {
      id: 'b1',
      imageUrl: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=1400&h=500&fit=crop&auto=format',
      titleAr: 'تقسيط ذكي بدون فوائد',
      titleEn: 'Smart Zero-Interest Installments',
      subtitleAr: 'اشتري منتجاتك المفضلة بأقساط شهرية ميسرة تبدأ من 0 مقدم',
      subtitleEn: 'Buy your favorites with easy monthly installments starting from 0 down payment',
      link: '/products',
      isActive: true,
      order: 1,
    },
    {
      id: 'b2',
      imageUrl: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1400&h=500&fit=crop&auto=format',
      titleAr: 'أحدث الإلكترونيات بالتقسيط',
      titleEn: 'Latest Electronics on Installments',
      subtitleAr: 'موبايلات ولابتوبات وأجهزة منزلية — خدمة في 27 محافظة',
      subtitleEn: 'Phones, Laptops & Home Appliances — Service in 27 Provinces',
      link: '/products',
      isActive: true,
      order: 2,
    },
  ],
};

// ============ EGYPTIAN PROVINCES ============
export const PROVINCES: Province[] = [
  { id: 'cairo', nameAr: 'القاهرة', nameEn: 'Cairo' },
  { id: 'giza', nameAr: 'الجيزة', nameEn: 'Giza' },
  { id: 'alexandria', nameAr: 'الإسكندرية', nameEn: 'Alexandria' },
  { id: 'luxor', nameAr: 'الأقصر', nameEn: 'Luxor' },
  { id: 'aswan', nameAr: 'أسوان', nameEn: 'Aswan' },
  { id: 'asyut', nameAr: 'أسيوط', nameEn: 'Asyut' },
  { id: 'beheira', nameAr: 'البحيرة', nameEn: 'Beheira' },
  { id: 'beni-suef', nameAr: 'بني سويف', nameEn: 'Beni Suef' },
  { id: 'dakahlia', nameAr: 'الدقهلية', nameEn: 'Dakahlia' },
  { id: 'damietta', nameAr: 'دمياط', nameEn: 'Damietta' },
  { id: 'fayoum', nameAr: 'الفيوم', nameEn: 'Fayoum' },
  { id: 'gharbia', nameAr: 'الغربية', nameEn: 'Gharbia' },
  { id: 'ismailia', nameAr: 'الإسماعيلية', nameEn: 'Ismailia' },
  { id: 'kafr-el-sheikh', nameAr: 'كفر الشيخ', nameEn: 'Kafr El Sheikh' },
  { id: 'matruh', nameAr: 'مطروح', nameEn: 'Matruh' },
  { id: 'minya', nameAr: 'المنيا', nameEn: 'Minya' },
  { id: 'monufia', nameAr: 'المنوفية', nameEn: 'Monufia' },
  { id: 'new-valley', nameAr: 'الوادي الجديد', nameEn: 'New Valley' },
  { id: 'north-sinai', nameAr: 'شمال سيناء', nameEn: 'North Sinai' },
  { id: 'port-said', nameAr: 'بور سعيد', nameEn: 'Port Said' },
  { id: 'qalyubia', nameAr: 'القليوبية', nameEn: 'Qalyubia' },
  { id: 'qena', nameAr: 'قنا', nameEn: 'Qena' },
  { id: 'red-sea', nameAr: 'البحر الأحمر', nameEn: 'Red Sea' },
  { id: 'sharqia', nameAr: 'الشرقية', nameEn: 'Sharqia' },
  { id: 'sohag', nameAr: 'سوهاج', nameEn: 'Sohag' },
  { id: 'south-sinai', nameAr: 'جنوب سيناء', nameEn: 'South Sinai' },
  { id: 'suez', nameAr: 'السويس', nameEn: 'Suez' },
];

// ============ MOCK PRODUCTS ============
export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Samsung Galaxy A55 5G',
    nameAr: 'سامسونج جالاكسي A55 5G',
    nameEn: 'Samsung Galaxy A55 5G',
    description: 'هاتف ذكي متطور بشاشة AMOLED 6.6 بوصة',
    descriptionAr: 'هاتف ذكي متطور بشاشة AMOLED 6.6 بوصة، ذاكرة 8GB RAM، تخزين 256GB',
    descriptionEn: 'Advanced smartphone with 6.6" AMOLED screen, 8GB RAM, 256GB storage',
    price: 18999,
    originalPrice: 21000,
    images: ['https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=600&h=600&fit=crop&auto=format'],
    category: 'phones',
    categoryAr: 'موبايلات',
    brand: 'Samsung',
    source: 'aman',
    sourceId: 'aman-001',
    isActive: true,
    stock: 25,
    lastSyncedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    specs: { 'الشاشة': '6.6 بوصة AMOLED', 'الذاكرة': '8GB', 'التخزين': '256GB', 'البطارية': '5000mAh' }
  },
  {
    id: 'p2',
    name: 'iPhone 15 Pro',
    nameAr: 'آيفون 15 برو',
    nameEn: 'iPhone 15 Pro',
    description: 'أحدث هواتف أبل بمعالج A17 Pro',
    descriptionAr: 'أحدث هواتف أبل بمعالج A17 Pro، شاشة ProMotion 6.1 بوصة',
    descriptionEn: 'Latest Apple phone with A17 Pro chip, 6.1" ProMotion display',
    price: 45999,
    originalPrice: 49000,
    images: ['https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=600&h=600&fit=crop&auto=format'],
    category: 'phones',
    categoryAr: 'موبايلات',
    brand: 'Apple',
    source: 'aman',
    sourceId: 'aman-002',
    isActive: true,
    stock: 15,
    lastSyncedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    specs: { 'الشاشة': '6.1 بوصة OLED', 'المعالج': 'A17 Pro', 'التخزين': '256GB', 'البطارية': '3274mAh' }
  },
  {
    id: 'p3',
    name: 'Lenovo IdeaPad Gaming 3',
    nameAr: 'لينوفو آيديا باد جيمينج 3',
    nameEn: 'Lenovo IdeaPad Gaming 3',
    description: 'لابتوب للألعاب بمعالج Intel Core i7',
    descriptionAr: 'لابتوب للألعاب بمعالج Intel Core i7، كارت NVIDIA GTX 1650، 16GB RAM',
    descriptionEn: 'Gaming laptop with Intel Core i7, NVIDIA GTX 1650, 16GB RAM',
    price: 32500,
    originalPrice: 35000,
    images: ['https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=600&h=600&fit=crop&auto=format'],
    category: 'laptops',
    categoryAr: 'لابتوبات',
    brand: 'Lenovo',
    source: 'aman',
    sourceId: 'aman-003',
    isActive: true,
    stock: 10,
    lastSyncedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    specs: { 'المعالج': 'Intel Core i7', 'الذاكرة': '16GB', 'التخزين': '512GB SSD', 'الشاشة': '15.6 بوصة' }
  },
  {
    id: 'p4',
    name: 'Samsung 55" Smart TV 4K',
    nameAr: 'سامسونج تليفزيون 55 بوصة 4K',
    nameEn: 'Samsung 55" Smart TV 4K',
    description: 'تليفزيون ذكي 4K بتقنية QLED',
    descriptionAr: 'تليفزيون ذكي 55 بوصة 4K بتقنية QLED، نظام Tizen',
    descriptionEn: '55" 4K Smart TV with QLED technology, Tizen OS',
    price: 22000,
    originalPrice: 25000,
    images: ['https://images.unsplash.com/photo-1593784991095-a205069470b6?w=600&h=600&fit=crop&auto=format'],
    category: 'tvs',
    categoryAr: 'شاشات وتليفزيونات',
    brand: 'Samsung',
    source: 'aman',
    sourceId: 'aman-004',
    isActive: true,
    stock: 8,
    lastSyncedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    specs: { 'الحجم': '55 بوصة', 'الدقة': '4K UHD', 'التقنية': 'QLED', 'نظام التشغيل': 'Tizen' }
  },
  {
    id: 'p5',
    name: 'LG Washing Machine 7kg',
    nameAr: 'غسالة LG 7 كيلو',
    nameEn: 'LG Washing Machine 7kg',
    description: 'غسالة أوتوماتيك 7 كيلو بتقنية AI',
    descriptionAr: 'غسالة أوتوماتيك 7 كيلو بتقنية الذكاء الاصطناعي، توفير في الطاقة A+++',
    descriptionEn: 'Automatic washing machine 7kg with AI technology, A+++ energy saving',
    price: 11500,
    originalPrice: 13000,
    images: ['https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?w=600&h=600&fit=crop&auto=format'],
    category: 'appliances',
    categoryAr: 'أجهزة منزلية',
    brand: 'LG',
    source: 'aman',
    sourceId: 'aman-005',
    isActive: true,
    stock: 20,
    lastSyncedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    specs: { 'الحمولة': '7 كيلو', 'السرعة': '1400 RPM', 'الطاقة': 'A+++', 'اللون': 'أبيض' }
  },
  {
    id: 'p6',
    name: 'PlayStation 5',
    nameAr: 'بلايستيشن 5',
    nameEn: 'PlayStation 5',
    description: 'جهاز ألعاب الجيل الجديد',
    descriptionAr: 'جهاز ألعاب الجيل الجديد PS5 بمعالج AMD Zen 2، SSD سريع 825GB',
    descriptionEn: 'Next-gen gaming console PS5 with AMD Zen 2, 825GB fast SSD',
    price: 19999,
    originalPrice: 22000,
    images: ['https://images.unsplash.com/photo-1607853202273-797f1c22a38e?w=600&h=600&fit=crop&auto=format'],
    category: 'gaming',
    categoryAr: 'ألعاب',
    brand: 'Sony',
    source: 'aman',
    sourceId: 'aman-006',
    isActive: true,
    stock: 12,
    lastSyncedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    specs: { 'المعالج': 'AMD Zen 2', 'الذاكرة': '16GB GDDR6', 'التخزين': '825GB SSD', 'الرسوميات': 'RDNA 2' }
  },
];

// ============ MOCK ORDERS ============
export const MOCK_ORDERS: Order[] = [
  {
    id: 'ord-001',
    customerId: 'cust-001',
    customerName: 'أحمد محمد علي',
    customerPhone: '01012345678',
    customerNationalId: '29901011234567',
    customerEmail: 'ahmed@gmail.com',
    customerProvince: 'cairo',
    customerAddress: 'شارع التحرير، الدقي، الجيزة',
    customerJob: 'مهندس',
    productId: 'p1',
    product: MOCK_PRODUCTS[0],
    installmentPlan: {
      months: 12,
      downPayment: 0,
      interestRate: 0,
      adminFee: 2,
      adminFeeAmount: 379,
      monthlyPayment: 1728,
      totalAmount: 20736,
      inquiryFee: 150,
    },
    status: 'under-review',
    supervisorId: 'sup-001',
    documents: {
      nationalIdFront: 'https://via.placeholder.com/400x250',
      nationalIdBack: 'https://via.placeholder.com/400x250',
      utilityBill: 'https://via.placeholder.com/400x250',
    },
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

// ============ MOCK SUPERVISORS ============
// NOTE: Real supervisors are loaded from Supabase database with password 'paynexb'
export const MOCK_SUPERVISORS: Supervisor[] = [
  {
    id: 'sup-001',
    name: 'محمد حسن',
    email: 'supervisor@paynex.com',
    phone: '01098765432',
    role: 'supervisor',
    province: 'cairo',
    workHoursStart: '09:00',
    workHoursEnd: '17:00',
    workDays: ['السبت', 'الأحد', 'الاثنين', 'الثلاثاء', 'الأربعاء'],
    target: 50,
    baseSalary: 3000,
    isActive: true,
    createdAt: new Date().toISOString(),
    wallet: {
      id: 'w-001',
      supervisorId: 'sup-001',
      totalFees: 4500,
      totalInstallmentsCollected: 85600,
      totalBalance: 90100,
      transactions: [],
      lastUpdated: new Date().toISOString(),
    },
    rewards: [],
    attendanceRecords: [],
  },
];

// Initialize test users
export function initTestUsers() {
  const usersKey = 'paynex_users';
  const existing = (() => { try { return JSON.parse(localStorage.getItem(usersKey) ?? '[]'); } catch { return []; } })();
  if (!existing.find((u: unknown) => u.email === 'aa@gmail.com')) {
    const testCustomer = {
      id: 'cust-test-001',
      name: 'أحمد محمد',
      email: 'aa@gmail.com',
      phone: '01011111111',
      role: 'customer',
      isActive: true,
      createdAt: new Date().toISOString(),
    };
    localStorage.setItem(usersKey, JSON.stringify([...existing, testCustomer]));
    localStorage.setItem('paynex_pass_cust-test-001', '000000');
  }
}

// ============ ADMIN CREDENTIALS ============
export const ADMIN_CREDENTIALS = {
  email: 'adminqastly@gmail.com',
  password: 'Mm.273199',
  user: {
    id: 'admin-001',
    name: 'المدير العام',
    email: 'adminqastly@gmail.com',
    role: 'admin' as const,
    isActive: true,
    createdAt: new Date().toISOString(),
  }
};

// ============ MOCK ANALYTICS ============
export const MOCK_ANALYTICS: Analytics = {
  totalOrders: 247,
  pendingOrders: 38,
  approvedOrders: 189,
  rejectedOrders: 20,
  totalRevenue: 4250000,
  totalCustomers: 198,
  ordersByProvince: [
    { province: 'القاهرة', count: 89, revenue: 1850000 },
    { province: 'الجيزة', count: 54, revenue: 980000 },
    { province: 'الإسكندرية', count: 41, revenue: 750000 },
    { province: 'الشرقية', count: 28, revenue: 420000 },
    { province: 'القليوبية', count: 35, revenue: 250000 },
  ],
  topProducts: [
    { product: 'سامسونج جالاكسي A55', count: 67 },
    { product: 'آيفون 15 برو', count: 45 },
    { product: 'لابتوب لينوفو جيمينج', count: 38 },
    { product: 'تليفزيون سامسونج 55"', count: 52 },
  ],
  supervisorPerformance: [
    { name: 'محمد حسن', orders: 89, revenue: 1850000, attendance: 95 },
    { name: 'فاطمة أحمد', orders: 67, revenue: 980000, attendance: 88 },
    { name: 'علي محمود', orders: 54, revenue: 750000, attendance: 92 },
  ],
  monthlyTrend: [
    { month: 'يناير', orders: 18, revenue: 320000 },
    { month: 'فبراير', orders: 22, revenue: 380000 },
    { month: 'مارس', orders: 28, revenue: 450000 },
    { month: 'أبريل', orders: 35, revenue: 580000 },
    { month: 'مايو', orders: 42, revenue: 720000 },
    { month: 'يونيو', orders: 38, revenue: 650000 },
  ],
};
